// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq-VBEYjtC_i1663tO-jpU0Ad4fsEBsFE',
    appId: '1:834989368009:web:c700c54823c9c5c4aba318',
    messagingSenderId: '834989368009',
    projectId: 'nsc-smart-cart',
    authDomain: 'nsc-smart-cart.firebaseapp.com',
    storageBucket: 'nsc-smart-cart.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmGTVkfQ5GEhLyI9r_nhUitT-RWrsZS74',
    appId: '1:834989368009:android:3ff3e04bd423bf01aba318',
    messagingSenderId: '834989368009',
    projectId: 'nsc-smart-cart',
    storageBucket: 'nsc-smart-cart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUlkQLG-PC-vFvac5h3tN8-T_RtG7T-qA',
    appId: '1:834989368009:ios:4b464022cdc76e94aba318',
    messagingSenderId: '834989368009',
    projectId: 'nsc-smart-cart',
    storageBucket: 'nsc-smart-cart.firebasestorage.app',
    iosBundleId: 'com.example.nfcApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUlkQLG-PC-vFvac5h3tN8-T_RtG7T-qA',
    appId: '1:834989368009:ios:4b464022cdc76e94aba318',
    messagingSenderId: '834989368009',
    projectId: 'nsc-smart-cart',
    storageBucket: 'nsc-smart-cart.firebasestorage.app',
    iosBundleId: 'com.example.nfcApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq-VBEYjtC_i1663tO-jpU0Ad4fsEBsFE',
    appId: '1:834989368009:web:27c207daa0850920aba318',
    messagingSenderId: '834989368009',
    projectId: 'nsc-smart-cart',
    authDomain: 'nsc-smart-cart.firebaseapp.com',
    storageBucket: 'nsc-smart-cart.firebasestorage.app',
  );
}
